# Tensors

## Tensors is a specialized multi-dimensional array desgined for mathematical and computational efficiency

#### Real World Example of tensors are:
##### 1. 0-Dimensional Tensor: Scalars/Rank 0 (Represents a single value often used for simple constants) E.g. 5.0

##### 2. 1-Dimensional Tensor: Vectors/Rank 1 (Respresents a sequence or a collection of values) E.g. Feature Vector in NLP for each word is represented as a 1D vector using embeddings [0.12, -0.84, 0.33]

##### 3. 2-Dimensional Tensor: Matrix/Rank 2 (Represents Tabular or Grid like data) E.g. A grayscale image [[0, 255, 128],[34, 90, 180]]

##### 4. 3-Dimensional Tensor: Coloured Images/Rank 3 (Adds a 3rd Dimension, often used for stacking data) E.g. RGB images

##### 5. 4-Dimensional Tensor: Batches of RGB Images/Rank 4 (Add the batch size as an additional dimension to 3D data) E.g.(batch size, width, height, channel)

##### 6. 5-Dimensional Tensor: Video Data/Rank 5 (Adds a time dimension for data that changes over time ) E.g. Video Frames (batch size, width, height, channel, time)

In [1]:
# Installing PyTorch
!pip install torch

  Using cached typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
  Using cached networkx-3.5-py3-none-any.whl.metadata (6.3 kB)
  Using cached jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
  Using cached setuptools-80.9.0-py3-none-any.whl.metadata (6.6 kB)
   ---------------------------------------- 0.0/241.3 MB ? eta -:--:--
   ---------------------------------------- 0.5/241.3 MB 5.5 MB/s eta 0:00:44
   ---------------------------------------- 1.3/241.3 MB 2.9 MB/s eta 0:01:24
   ---------------------------------------- 1.8/241.3 MB 2.7 MB/s eta 0:01:28
   ---------------------------------------- 2.4/241.3 MB 2.6 MB/s eta 0:01:31
   ---------------------------------------- 2.9/241.3 MB 2.7 MB/s eta 0:01:27
    --------------------------------------- 3.7/241.3 MB 2.7 MB/s eta 0:01:28
    --------------------------------------- 4.2/241.3 MB 2.8 MB/s eta 0:01:27
    --------------------------------------- 4.7/241.3 MB 2.7 MB/s eta 0:01:27
    --------------------------------

In [2]:
# Importing PyTorch
import torch
print("PyTorch version:", torch.__version__)

d:\Main_PyTorch_Git\PyTorch-Quick-Go\venv\Lib\site-packages\torch\_subclasses\functional_tensor.py:279: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\pytorch\torch\csrc\utils\tensor_numpy.cpp:81.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


PyTorch version: 2.8.0+cpu


In [3]:
# Checking for GPU availability
if torch.cuda.is_available():
    device = torch.device("cuda")
    print("GPU is available. Using GPU:", torch.cuda.get_device_name(0))
else:
    device = torch.device("cpu")
    print("GPU not available. Using CPU.")

GPU not available. Using CPU.


# Creating Tensors

In [6]:
# Using Empty Function for Tensor Creation
x = torch.empty(3, 4)
print("Empty Tensor: \n", x)
print("Shape of Tensor:", x.shape, "\n")
# Using Zeros Function for Tensor Creation
y = torch.zeros(3, 4)
print("Zeros Tensor:\n", y)
print("Shape of Tensor:", y.shape, "\n")

# Using Ones Function for Tensor Creation
z = torch.ones(3, 4)
print("Ones Tensor:\n", z)
print("Shape of Tensor:", z.shape, "\n")

# Using Random Function for Tensor Creation
r = torch.rand(3, 4)
print("Random Tensor:\n", r)
print("Shape of Tensor:", r.shape, "\n")

# Using Seed for Reproducibility
torch.manual_seed(42)
r_seeded = torch.rand(3, 4)
print("Seeded Random Tensor:\n", r_seeded)
print("Shape of Tensor:", r_seeded.shape, "\n")

# Creating Tensors
a = torch.tensor([1, 2, 3, 4])
b = torch.tensor([[1, 2], [3, 4]])
print("1D Tensor:\n", a)
print("Shape of 1D Tensor:", a.shape, "\n")
print("2D Tensor:\n", b)
print("Shape of 2D Tensor:", b.shape, "\n")



Empty Tensor: 
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Shape of Tensor: torch.Size([3, 4]) 

Zeros Tensor:
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Shape of Tensor: torch.Size([3, 4]) 

Ones Tensor:
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
Shape of Tensor: torch.Size([3, 4]) 

Random Tensor:
 tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
Shape of Tensor: torch.Size([3, 4]) 

Seeded Random Tensor:
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
Shape of Tensor: torch.Size([3, 4]) 

1D Tensor:
 tensor([1, 2, 3, 4])
Shape of 1D Tensor: torch.Size([4]) 

2D Tensor:
 tensor([[1, 2],
        [3, 4]])
Shape of 2D Tensor: torch.Size([2, 2]) 



# Tensor Creation for Special Purpose

In [7]:
lin = torch.linspace(0, 10, steps=5)
print("Linspace Tensor:\n", lin)
print("Shape of Linspace Tensor:", lin.shape, "\n")

# Identiy Matrix
eye = torch.eye(3)
print("Identity Matrix:\n", eye)
print("Shape of Identity Matrix:", eye.shape, "\n")

# Full Tensor
full = torch.full((3, 4), 7)
print("Full Tensor:\n", full)
print("Shape of Full Tensor:", full.shape, "\n")


Linspace Tensor:
 tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
Shape of Linspace Tensor: torch.Size([5]) 

Identity Matrix:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
Shape of Identity Matrix: torch.Size([3, 3]) 

Full Tensor:
 tensor([[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]])
Shape of Full Tensor: torch.Size([3, 4]) 



# Attributes of Tensors

In [8]:
t = torch.rand(3, 4)
print("Tensor:\n", t)
print("Shape:", t.shape)
print("Data Type:", t.dtype)
print("Device:", t.device)
print("Number of Dimensions:", t.ndim)
print("Size:", t.size())


Tensor:
 tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
Shape: torch.Size([3, 4])
Data Type: torch.float32
Device: cpu
Number of Dimensions: 2
Size: torch.Size([3, 4])


# Creating Tensors from Exisiting Tensors

In [10]:
# New from Exisiting Tensors
t = torch.rand(3, 4)
t_zeros = torch.zeros_like(t) # Same shape as t
t_ones = torch.ones_like(t)
t_rand = torch.rand_like(t, dtype=torch.float16) # Specifying a different data type
print("Original Tensor:\n", t, "\n")
print("Zeros Tensor with same shape as Original:\n", t_zeros, "\n")
print("Ones Tensor with same shape as Original:\n", t_ones, "\n")
print("Random Tensor with same shape as Original but different data type:\n", t_rand)


Original Tensor:
 tensor([[0.7539, 0.1952, 0.0050, 0.3068],
        [0.1165, 0.9103, 0.6440, 0.7071],
        [0.6581, 0.4913, 0.8913, 0.1447]]) 

Zeros Tensor with same shape as Original:
 tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) 

Ones Tensor with same shape as Original:
 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) 

Random Tensor with same shape as Original but different data type:
 tensor([[0.8994, 0.3154, 0.0098, 0.4102],
        [0.0811, 0.6333, 0.1890, 0.2930],
        [0.1538, 0.0063, 0.1177, 0.9966]], dtype=torch.float16)


# Tensor Data Types

In [11]:
# Data Types in PyTorch
int_tensor = torch.tensor([1, 2, 3], dtype=torch.int32)
float_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
double_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float64)
print("Integer Tensor:", int_tensor, "with data type:", int_tensor.dtype)
print("Float Tensor:", float_tensor, "with data type:", float_tensor.dtype)
print("Double Tensor:", double_tensor, "with data type:", double_tensor.dtype)
# Changing Data Types
float_to_int = float_tensor.to(torch.int32) # or 
print("Float to Int using to():", float_to_int, "with data type:", float_to_int.dtype)

float_tensor.int()
print("Float to Int using int():", float_tensor.int(), "with data type:", float_tensor.int().dtype)




Integer Tensor: tensor([1, 2, 3], dtype=torch.int32) with data type: torch.int32
Float Tensor: tensor([1., 2., 3.]) with data type: torch.float32
Double Tensor: tensor([1., 2., 3.], dtype=torch.float64) with data type: torch.float64
Float to Int using to(): tensor([1, 2, 3], dtype=torch.int32) with data type: torch.int32
Float to Int using int(): tensor([1, 2, 3], dtype=torch.int32) with data type: torch.int32


# Mathematical Operations
### 1. Scalar Operations

In [12]:
t = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
# Adding a Scalar
t_add = t + 5
print("Original Tensor:\n", t)
print("After Adding 5:\n", t_add, "\n")
# Subtracting a Scalar
t_sub = t - 2
print("After Subtracting 2:\n", t_sub, "\n")
# Multiplying by a Scalar
t_mul = t * 3
print("After Multiplying by 3:\n", t_mul, "\n")
# Dividing by a Scalar
t_div = t / 2
print("After Dividing by 2:\n", t_div, "\n")
# Exponentiation
t_exp = t ** 2
print("After Squaring:\n", t_exp, "\n")
# Floor Division
t_floordiv = t // 2
print("After Floor Division by 2:\n", t_floordiv, "\n")
# Modulus
t_mod = t % 2
print("After Modulus 2:\n", t_mod, "\n")

Original Tensor:
 tensor([[1., 2.],
        [3., 4.]])
After Adding 5:
 tensor([[6., 7.],
        [8., 9.]]) 

After Subtracting 2:
 tensor([[-1.,  0.],
        [ 1.,  2.]]) 

After Multiplying by 3:
 tensor([[ 3.,  6.],
        [ 9., 12.]]) 

After Dividing by 2:
 tensor([[0.5000, 1.0000],
        [1.5000, 2.0000]]) 

After Squaring:
 tensor([[ 1.,  4.],
        [ 9., 16.]]) 

After Floor Division by 2:
 tensor([[0., 1.],
        [1., 2.]]) 

After Modulus 2:
 tensor([[1., 0.],
        [1., 0.]]) 



### 2. Element-wise Operations

In [ ]:
x = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
y = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)

# Element-wise Addition
t_add = x + y
print("Element-wise Addition:\n", t_add, "\n")

# Element-wise Subtraction
t_sub = x - y
print("Element-wise Subtraction:\n", t_sub, "\n")

# Element-wise Multiplication
t_mul = x * y
print("Element-wise Multiplication:\n", t_mul, "\n")

# Element-wise Division
t_div = x / y
print("Element-wise Division:\n", t_div, "\n")


Element-wise Addition:
 tensor([[ 6.,  8.],
        [10., 12.]]) 

Element-wise Subtraction:
 tensor([[-4., -4.],
        [-4., -4.]]) 

Element-wise Multiplication:
 tensor([[ 5., 12.],
        [21., 32.]]) 

Element-wise Division:
 tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]]) 



In [ ]:
# Element-wise Exponentiation
t_exp = x ** y
print("Element-wise Exponentiation:\n", t_exp, "\n")

# Element-wise Floor Division
t_floordiv = x // y
print("Element-wise Floor Division:\n", t_floordiv, "\n")

# Element-wise Modulus
t_mod = x % y
print("Element-wise Modulus:\n", t_mod, "\n")

# Absolute Value
t_abs = torch.abs(x - y)
print("Absolute Value of (x - y):\n", t_abs, "\n")

# Negation
t_neg = -x
print("Negation of x:\n", t_neg, "\n")

# Rounding
t_round = torch.round(torch.tensor([1.2, 2.5, 3.7]))
print("Rounding:\n", t_round, "\n")

# Ceiling
t_ceil = torch.ceil(torch.tensor([1.2, 2.5, 3.7]))
print("Ceiling:\n", t_ceil, "\n")

# Floor
t_floor = torch.floor(torch.tensor([1.2, 2.5, 3.7]))
print("Floor:\n", t_floor, "\n")

# Clamp
t_clamp = torch.clamp(torch.tensor([-1.0, 0.5, 2.0, 3.5]), min=0.0, max=2.0)
print("Clamped Tensor (0.0 to 2.0):\n", t_clamp, "\n")



Element-wise Exponentiation:
 tensor([[1.0000e+00, 6.4000e+01],
        [2.1870e+03, 6.5536e+04]]) 

Element-wise Floor Division:
 tensor([[0., 0.],
        [0., 0.]]) 

Element-wise Modulus:
 tensor([[1., 2.],
        [3., 4.]]) 

Absolute Value of (x - y):
 tensor([[4., 4.],
        [4., 4.]]) 

Negation of x:
 tensor([[-1., -2.],
        [-3., -4.]]) 



### 3. Reduction Operation

In [16]:
e = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32)
print("Original Tensor:\n", e, "\n")

# Sum of all elements
sum_all = torch.sum(e)
print("Sum of all elements:", sum_all.item(), "\n")

# Sum along rows (dim=0)
sum_rows = torch.sum(e, dim=0)
print("Sum along rows (dim=0):", sum_rows, "\n")

# Sum along columns (dim=1)
sum_cols = torch.sum(e, dim=1)
print("Sum along columns (dim=1):", sum_cols, "\n")

# Mean of all elements
mean_all = torch.mean(e)
print("Mean of all elements:", mean_all.item(), "\n")

# Mean along rows (dim=0)
mean_rows = torch.mean(e, dim=0)
print("Mean along rows (dim=0):", mean_rows, "\n")

# Mean along columns (dim=1)
mean_cols = torch.mean(e, dim=1)
print("Mean along columns (dim=1):", mean_cols, "\n")

# Median of all elements
median_all = torch.median(e)
print("Median of all elements:", median_all.item(), "\n")

# Median along rows (dim=0)
median_rows = torch.median(e, dim=0).values
print("Median along rows (dim=0):", median_rows, "\n")

# Median along columns (dim=1)
median_cols = torch.median(e, dim=1).values
print("Median along columns (dim=1):", median_cols, "\n")


# Standard Deviation of all elements
std_all = torch.std(e)
print("Standard Deviation of all elements:", std_all.item(), "\n")

# Variance of all elements
var_all = torch.var(e)
print("Variance of all elements:", var_all.item(), "\n")

# Argmax of all elements
argmax_all = torch.argmax(e)
print("Argmax of all elements (index):", argmax_all.item(), "\n")

# Argmin of all elements
argmin_all = torch.argmin(e)
print("Argmin of all elements (index):", argmin_all.item(), "\n")


Original Tensor:
 tensor([[1., 2., 3.],
        [4., 5., 6.]]) 

Sum of all elements: 21.0 

Sum along rows (dim=0): tensor([5., 7., 9.]) 

Sum along columns (dim=1): tensor([ 6., 15.]) 

Mean of all elements: 3.5 

Mean along rows (dim=0): tensor([2.5000, 3.5000, 4.5000]) 

Mean along columns (dim=1): tensor([2., 5.]) 

Median of all elements: 3.0 

Median along rows (dim=0): tensor([1., 2., 3.]) 

Median along columns (dim=1): tensor([2., 5.]) 

Standard Deviation of all elements: 1.8708287477493286 

Variance of all elements: 3.5 

Argmax of all elements (index): 5 

Argmin of all elements (index): 0 



### 4. Matrix Operations

In [24]:
# Matrix Operations
A = torch.tensor([[1, 2], [3, 4]], dtype=torch.float32)
B = torch.tensor([[5, 6], [7, 8]], dtype=torch.float32)
print("Matrix A:\n", A, "\n")
print("Matrix B:\n", B, "\n")

# Matrix Multiplication
mat_mul = torch.matmul(A, B)
print("Matrix Multiplication (A @ B):\n", mat_mul, "\n")

# Alternatively, using the @ operator
mat_mul_op = A @ B
print("Matrix Multiplication using @ operator (A @ B):\n", mat_mul_op)

# Dot Product 
v1 = torch.tensor([1,2,3])
v2 = torch.tensor([4,5,6])
print("Vector 1", v1)
print("Vector 2", v2)
print("Dot Product (v1 v2)\n", v1.dot(v2))

# Transpose 
trans = torch.transpose(A, 0, 1)
print("Transpose of A", trans)

# Determinant
det = torch.det(A)
print("Deteminant of A", det)

# Inverse 
inv = torch.inverse(B)
print("Inverse of B", inv)

Matrix A:
 tensor([[1., 2.],
        [3., 4.]]) 

Matrix B:
 tensor([[5., 6.],
        [7., 8.]]) 

Matrix Multiplication (A @ B):
 tensor([[19., 22.],
        [43., 50.]]) 

Matrix Multiplication using @ operator (A @ B):
 tensor([[19., 22.],
        [43., 50.]])
Vector 1 tensor([1, 2, 3])
Vector 2 tensor([4, 5, 6])
Dot Product (v1 v2)
 tensor(32)
Transpose of A tensor([[1., 3.],
        [2., 4.]])
Deteminant of A tensor(-2.)
Inverse of B tensor([[-4.0000,  3.0000],
        [ 3.5000, -2.5000]])
